<?php

namespace Database\Seeders\Material;

use App\Models\Log\LogTransaction;
use App\Models\Master\Material\MaterialGroup;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialGroupSeeder extends Seeder
{
    private $table = 'material_group_master';
    public function run(): void
    {
        $now = Carbon::now();
        // product_group (247 rows)
        $data = [
            ['id_category' => 1, 'product_group' => 'AC16/90', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC18/98', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC18IRR', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC18W/75', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC18W/80', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC18W/98', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68 SA', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68 TA', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68 TA-C', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/10', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/15', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/20', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/25', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/40', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/40D', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68/50', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'AC68SA', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'ACID 18 IRR', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'ACID 68 IRR', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'ACID 68 PURCHASE', 'created_at' => $now],
            ['id_category' => 1, 'product_group' => 'CRUDE ACID 68', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC06', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC06-C', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC08', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC10/90', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC10/98', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC60', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC8/99', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC80', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC80-C', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC810', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC810 (EXCESS)', 'created_at' => $now],
            ['id_category' => 2, 'product_group' => 'AC810-C', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 12-1', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-1', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-10', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-11', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-11.5', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-12', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-15', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-15/85', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-15/90', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-2', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-3', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-4', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-5', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-6', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-7', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-7.8', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-7.8/90', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-7/90', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-8', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24-9', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 24L-12', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 26-2', 'created_at' => $now],
            ['id_category' => 3, 'product_group' => 'AEO 26-3', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA16', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA16 IRR', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA16/99', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA18', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA18/95', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA18/98', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA18/99', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA18DEO', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA20', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA22', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68/30', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68/50', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68/60', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68/65', 'created_at' => $now],
            ['id_category' => 4, 'product_group' => 'FA68/70', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA12', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA12/99', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA14', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA14 IRR', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA14/99', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA24', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA24/55', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA24-C', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA26', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA26-C', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA28', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA46', 'created_at' => $now],
            ['id_category' => 5, 'product_group' => 'FA88', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA02', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA10', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA10 IRR', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA10/99', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA6', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA6/99', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA62', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA8', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA8/99', 'created_at' => $now],
            ['id_category' => 6, 'product_group' => 'FA80', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ACID OIL', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ACID OIL A', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ACID OIL B', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ACID OIL C', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ACID OIL D', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'BDAC BM', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'BDFA BM11', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'BDG', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'BDME', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'CRUDE WAX BF', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ECOROL WAX U', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ECOROL-WAX B', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ECOROL-WAX BF', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ECOROL-WAX M', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'EWAXBM', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'FAHE-2', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'FFA', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'FILTER CAKE', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'HC', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEFA', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEFA 1', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEFA 2', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEFA 3', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEFA M', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEME', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'LEUFA', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'ME6/65', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'SEPARATED FAT', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'SKIMMED OIL M', 'created_at' => $now],
            ['id_category' => 7, 'product_group' => 'UFA W36', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'CARBON.A', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'CATALYST', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'CH3OH', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'CH3ONA', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'CHE', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'DEA', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'FECl3', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'FILTER AID', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'H2O2', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'H2SO4', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'H3PO4', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'HCl', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'MeOH3', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'MeOH65', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'MeOH88', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'NAH2PO2', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'NaOH', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'OTHERS', 'created_at' => $now],
            ['id_category' => 8, 'product_group' => 'Ti(OCH(CH3)2)4', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'AMISOL', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'AMISOL-3G', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'GTCC', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'GTCC 70/30', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'GTCC-C', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'LO75', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'OE', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'OLO', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'TMPTCC', 'created_at' => $now],
            ['id_category' => 9, 'product_group' => 'TMPTO', 'created_at' => $now],
            ['id_category' => 10, 'product_group' => 'ROFAMIN', 'created_at' => $now],
            ['id_category' => 11, 'product_group' => 'GLY', 'created_at' => $now],
            ['id_category' => 11, 'product_group' => 'GLY EX SEC 116', 'created_at' => $now],
            ['id_category' => 11, 'product_group' => 'GLY-CNO', 'created_at' => $now],
            ['id_category' => 11, 'product_group' => 'GLY-H', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME16', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME18S', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME18U', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME18W', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68/25', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68/30', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68/40', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68IRR', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68SA', 'created_at' => $now],
            ['id_category' => 12, 'product_group' => 'ME68TA', 'created_at' => $now],
            ['id_category' => 13, 'product_group' => 'ME10', 'created_at' => $now],
            ['id_category' => 13, 'product_group' => 'ME8', 'created_at' => $now],
            ['id_category' => 13, 'product_group' => 'ME80', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'CNO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'CPKO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'CPKOL', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'CPO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'CPO-DMO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'EO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'RBDPKO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'RBDPKOL', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'RBDPO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'RBDPOL-DMO', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'RBDPS', 'created_at' => $now],
            ['id_category' => 14, 'product_group' => 'TMP', 'created_at' => $now],
            ['id_category' => 15, 'product_group' => 'SORBITOL TFF', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'DIST. UFA HIGH IV', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'DIST. UFA LOW IV', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'ROFALAN 7020', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'STEARINE UFA', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA100', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA50/55', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA50/55P', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA60/65', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA70/75', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA70/75P', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA80/85', 'created_at' => $now],
            ['id_category' => 16, 'product_group' => 'UFA90/95', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC810', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC810/70', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC24', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC24-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC26', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC26-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC28', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'C.F.ACID', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CAC', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CAC68', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CAC-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA 1', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA 2', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA0608', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA28', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA60', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA68', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFA80', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CFADEO', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CME', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CME80', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CME-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CROE', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CRUDE UFA HIGH IV', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'CRUDE UFA LOW IV', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'DAOIL', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ECOROL-WAX BB', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ESTEROIL', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-C-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-II', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-W', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-WT', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'Gly-WT-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME24', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME26', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME26-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME28', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME60', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'ME80', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'OLEIN UFA', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'RGW', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'TREATED OIL', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'TREATED OIL-C', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'WE', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC68/15', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC68/20', 'created_at' => $now],
            ['id_category' => 17, 'product_group' => 'AC68/40', 'created_at' => $now],
        ];

        MaterialGroup::truncate();
        DB::table($this->table)->insert($data);

        // Increment id sequence
        DB::statement("SELECT setval('{$this->table}_id_seq', (SELECT MAX(id) FROM {$this->table}))");

        $count = count($data);
        LogTransaction::insert([
            'log_module' => 'MasterData',
            'log_type' => 'SEED',
            'log_model' => 'MATERIAL_GROUP',
            'log_description' => "SEED MATERIAL_GROUP $count DATA",
        ]);
    }
}
