FROM nginx:latest

# Copy the custom Nginx configuration
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# use PHP image (previously built) as source
COPY --from=pspa_scm /var/www/html/public /var/www/html/public
RUN chmod -R 755 /var/www/html/public

# Expose port
EXPOSE 443
